name: example_project
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - jupyter=1.0.0
  - matplotlib=3.1.1
  - numpy=1.17.2
  - pandas=0.25.1
  - pyarrow=0.14.1
  - pytables=3.5.2
  - python=3.7.3
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - seaborn=0.9.0
  - snakemake=5.6.0

